/*
 * GreekSchools Data Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type PublicKey struct {

	PublicKey string `json:"publicKey"`
}

// AssertPublicKeyRequired checks if the required fields are not zero-ed
func AssertPublicKeyRequired(obj PublicKey) error {
	elements := map[string]interface{}{
		"publicKey": obj.PublicKey,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecursePublicKeyRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of PublicKey (e.g. [][]PublicKey), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePublicKeyRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPublicKey, ok := obj.(PublicKey)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPublicKeyRequired(aPublicKey)
	})
}
