/*
 * GreekSchools Data Service API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ModelError struct {

	Timestamp time.Time `json:"timestamp,omitempty"`

	Error string `json:"error,omitempty"`

	Message string `json:"message,omitempty"`

	Path string `json:"path,omitempty"`
}

// AssertModelErrorRequired checks if the required fields are not zero-ed
func AssertModelErrorRequired(obj ModelError) error {
	return nil
}

// AssertRecurseModelErrorRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ModelError (e.g. [][]ModelError), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseModelErrorRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aModelError, ok := obj.(ModelError)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertModelErrorRequired(aModelError)
	})
}
